version: "3.7"
services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile.prd
        ports:
            - "7000:7000"
        env_file: ./.env
        environment:
            NODE_ENV: production

        networks:
            - jobhub-network-prod

networks:
    jobhub-network-prod:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local
